---
name: tagged-release
on:
  push:
    tags:
      - v*
jobs:
  tagged-release:
    name: Tagged Release
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build and test
        run: autoreconf -i && ./configure && make distcheck
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: "*.tar.xz"
